---
- hosts: haproxy
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    
    - name: Install HAProxy
      apt:
        name: haproxy
        state: present

    - name: Configure HAProxy
      copy:
        dest: /etc/haproxy/haproxy.cfg
        content: |
          frontend k8s-api
            bind *:6443
            mode tcp
            default_backend k8s-api
            timeout client 30s

          backend k8s-api
            mode tcp
            option tcp-check
            balance roundrobin
            default-server inter 10s downinter 5s rise 2 fall 2 slowstart 60s maxconn 250 maxqueue 256 weight 100
            server controlplane-1 10.0.2.15:6443 check
            server controlplane-3 192.168.56.11:6443 check
            server controlplane-2 192.168.56.12:6443 check
            timeout connect 5s
            timeout server 30s


    - name: Restart HAProxy
      systemd:
        name: haproxy
        state: restarted