#
# Worker Node
#
- hosts: worker
  become: yes
  vars_files:
    - vars.yml
  vars:
    saved_join_command: "{{ lookup('file', './join-command') }}"
  tasks:

    # Join server on k8s Cluster as Worker Node
    - name: Run the saved join command on another server
      command: "{{ saved_join_command }}"


