
- name: Include playbook kubernetes Common
  ansible.builtin.import_playbook: k8s_common.yml

- name: Include playbook kubernetes Control Plane
  ansible.builtin.import_playbook: k8s_control_plane.yml

- name: Include playbook kubernetes Worker Node
  ansible.builtin.import_playbook: k8s_worker_node.yml
